---
- name: Install frequently used packages (htop, wget, etc)
  become:      yes
  action: >
    {{ ansible_pkg_mgr }} name={{ item }} state=present update_cache=yes
  with_items:
    - wget
    - unzip
    - stunnel
    - tcpdump
    - java-1.8.0-openjdk-devel
    - stunnel

- name: Adjusting max SO_RCVBUF (Aeron)
  sysctl:
    name:         net.core.rmem_max
    value:        2097152
    sysctl_set:   yes
    state:        present
    reload:       yes
  become:         yes

- name: Adjusting max SO_SNDBUF (Aeron)
  sysctl:
    name:         net.core.wmem_max
    value:        2097152
    sysctl_set:   yes
    state:        present
    reload:       yes
  become:         yes
